### ISSUE TITLE
关于报错

### ISSUE THREAD

**Issue by HTTZYT-lt** [Hakuuyosei/QQHistoryExport#11]
parse :正在进行数据库查询，若数据库比较大，索引建立时间可能比较长
parse :数据库查询发生no such table: TroopMemberInfo错误：execute 解析停止!
这是output/parse_log.txt里面两行报错        系统版本是win11的 软件版本是0.2.0的那个
然后就是关于qqnt的内容 我在网上看到的都很傻 手机的qq现在也都是nt架构的嘛

**Comment by SendToSouthEast** [comment]
是的，现在手机QQ都是NT架构，在界面上没有任何区别，就是看版本号，8.9.63以上版本可能就是。
本项目发布后不久，QQ就大面积更新NT版本了，所以本项目后来就很少维护了

**Comment by HTTZYT-lt** [comment]
> 是的，现在手机QQ都是NT架构，在界面上没有任何区别，就是看版本号，8.9.63以上版本可能就是。 本项目发布后不久，QQ就大面积更新NT版本了，所以本项目后来就很少维护了

这样子嘛 感谢你们的付出 为我们提供了便利
