### ISSUE TITLE
数据解析出现问题

### ISSUE THREAD

**Issue by ODRAN07** [Hakuuyosei/QQHistoryExport#5]
附图，虽然显示解析未发生错误，但却是0条消息。
![NXW_KV7M J7 @BHFJ0)(QB8](https://github.com/Hakuuyosei/QQHistoryExport/assets/145624679/05751060-b422-499f-b55c-4a999e2236ae)
parse_log显示的信息是：“parse :正在进行数据库查询，若数据库比较大，索引建立时间可能比较长
parse :数据库查询发生no such table: mr_troop_2A17910B1CFDCBC69A0710EACB931B35_New错误：execute 解析停止!
”

**Comment by ODRAN07** [comment]
[谢谢回复。我只填写了以下几个部分，检查过没有填错。保存的数据也不算隐私，可以发送。
![1695306897946](https://github.com/Hakuuyosei/QQHistoryExport/assets/145624679/fa4d67db-5ed3-4621-b2e9-6822d6b492aa)

**Comment by ODRAN07** [comment]
谢谢回复，我只填写了以下几项，并且确认过没有填错。数据也不算私密，我会单独发来测试。
![`XSERB)}N }4~8O3)R5L0`G](https://github.com/Hakuuyosei/QQHistoryExport/assets/145624679/801616b9-8709-4cc3-99ed-45e2a90f9d2f)

**Comment by ODRAN07** [comment]
不好意思，文件量实在太大。发不了邮件。我已经加入了该项目的交流IM，账号是ORANAGE，我想可以在那里进行下一步的交流。

**Comment by SendToSouthEast** [comment]
（虽然在IM交流过了但是在这里概括一下供别人参考）
显示了错误但又说解析没错误，但是0条消息的问题可能是两个数据库读取顺序（以及附近代码）的问题，该return的时候没return，该问题在上周已经在master中修复。

然后您那边拿不到消息，您说消息是比较久远，我觉得可能还是上一个问题（两个数据库读取顺序）的原因。

已发布0.2.0版本。您可以试试。

此外，我我这边没有太久远的样本，你那边遇到什么问题了，再交流解决。

**Comment by ODRAN07** [comment]
从 Windows 版邮件发送

发件人: SendToSouthEast
发送时间: 2023年9月23日 23:38
收件人: Hakuuyosei/QQHistoryExport
抄送: ODRAN07; Author
主题: Re: [Hakuuyosei/QQHistoryExport] 数据解析出现问题 (Issue #5)

（虽然在IM交流过了但是在这里概括一下供别人参考）
显示了错误但又说解析没错误，但是0条消息的问题可能是两个数据库读取顺序（以及附近代码）的问题，该return的时候没return，该问题在上周已经在master中修复。
然后您那边拿不到消息，您说消息是比较久远，我觉得可能还是上一个问题（两个数据库读取顺序）的原因。
已发布0.2.0版本。您可以试试。
此外，我我这边没有太久远的样本，你那边遇到什么问题了，再交流解决。

**Comment by SendToSouthEast** [comment]
总结如下：
数据库中有群信息却没有表引发两个提示错误，已修复

数据库中有群信息却没有表的原因是更新了QQNT版本，数据被转移到了新的数据库，无法解析。
