### ISSUE TITLE
已解散的群无法找到，提示查无此群

### ISSUE THREAD

**Issue by T0k1ta** [Hakuuyosei/QQHistoryExport#6]
如题，但是[之前的这个工具](https://github.com/Yiyiyimu/QQ-History-Backup)是可以找到已解散的群并且可以导出。这有点奇怪，但我不懂代码，还请开发组帮忙定位一下问题在哪，谢谢！

![1](https://github.com/Hakuuyosei/QQHistoryExport/assets/51959691/a1fa18cd-7844-488d-8f98-5833b28aa12c)
![2](https://github.com/Hakuuyosei/QQHistoryExport/assets/51959691/3ae04403-321f-4b98-9c40-312a3e3f836f)

**Comment by SendToSouthEast** [comment]
你试试看别的群是否能正常找到和导出？
查表算法都是一样的，确实有些奇怪

**Comment by snowman** [comment]
我服了，群通知显示被管理员踢了，群聊对话框直接不见了，想查看群名片也看不了，这么垃圾的聊天软件，聊天记录直接没了，QQ启动！记忆清空！

**Comment by SendToSouthEast** [comment]
> 我服了，群通知显示被管理员踢了，群聊对话框直接不见了，想查看群名片也看不了，这么垃圾的聊天软件，聊天记录直接没了，QQ启动！记忆清空！ 

如果您找不到群号，可以尝试在python环境中运行源码，在解析之前，控制台会打印出你所有的有聊天记录的群群号和名称，这个方法也许能找到您的群。
不过也要注意本项目不支持QQNT版本。
另：qq确实狗屎！
