### ISSUE TITLE
[BUG]QQ头像下载接口失效

### ISSUE THREAD

**Issue by YatinYin** [Hakuuyosei/QQHistoryExport#9]
新接口：
`https://q.qlogo.cn/g?b=qq&nk={qq号}&s=640`
s参数为尺寸 (100/160/640)

**Comment by ahzvenol** [comment]
并未测试出旧接口异常？可否给出例子？

**Comment by YatinYin** [comment]
我用的releases中的v0.2.0版本，在下载头像的时候提示发生错误，请手动下载。
不过好奇怪，我刚刚试了一下，[src/avatarDownload/download.py](https://github.com/Hakuuyosei/QQHistoryExport/blob/master/src/avatarDownload/download.py)中的`https://q1.qlogo.cn/g?b=qq&nk={qq号}&s=640`和`https://q.qlogo.cn/g?b=qq&nk={qq号}&s=640`两个接口现在都能用，难道接口可用性和IP属地有关🤔？我之前和现在不在同一个省。

**Comment by SendToSouthEast** [comment]
> 我用的releases中的v0.2.0版本，在下载头像的时候提示发生错误，请手动下载。
> 不过好奇怪，我刚刚试了一下，[src/avatarDownload/download.py](https://github.com/Hakuuyosei/QQHistoryExport/blob/master/src/avatarDownload/download.py)中的`https://q1.qlogo.cn/g?b=qq&nk={qq号}&s=640`和`https://q.qlogo.cn/g?b=qq&nk={qq号}&s=640`两个接口现在都能用，难道接口可用性和IP属地有关🤔？我之前和现在不在同一个省。

看是不是代理没关🤔

**Comment by YatinYin** [comment]
刚刚把releases的版本下载下来复现了一下，在不关代理的情况下会报错
`HTTPSConnectionPool(host='q1.qlogo.cn', port=443): Max retries exceeded with url: /g?b=qq&nk=**********&s=640 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))`. (*号处为QQ号)，关了代理就好了。
当时没想到，还以为是接口失效了，就把代码下载下来搜了一个接口，修改一下编译运行。

好尴尬啊🤡
